In [2]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import RandomForestClassifier
import joblib

In [3]:
df = pd.read_csv('canada_per_capita_income.csv')
df.head()

   year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [4]:
X = df.drop(columns=['per capita income (US$)'])
X

    year
0   1970
1   1971
2   1972
3   1973
4   1974
5   1975
6   1976
7   1977
8   1978
9   1979
10  1980
11  1981
12  1982
13  1983
14  1984
15  1985
16  1986
17  1987
18  1988
19  1989
20  1990
21  1991
22  1992
23  1993
24  1994
25  1995
26  1996
27  1997
28  1998
29  1999
30  2000
31  2001
32  2002
33  2003
34  2004
35  2005
36  2006
37  2007
38  2008
39  2009
40  2010
41  2011
42  2012
43  2013
44  2014
45  2015
46  2016

In [5]:
Y = df['per capita income (US$)']
Y

0      3399.299037
1      3768.297935
2      4251.175484
3      4804.463248
4      5576.514583
5      5998.144346
6      7062.131392
7      7100.126170
8      7247.967035
9      7602.912681
10     8355.968120
11     9434.390652
12     9619.438377
13    10416.536590
14    10790.328720
15    11018.955850
16    11482.891530
17    12974.806620
18    15080.283450
19    16426.725480
20    16838.673200
21    17266.097690
22    16412.083090
23    15875.586730
24    15755.820270
25    16369.317250
26    16699.826680
27    17310.757750
28    16622.671870
29    17581.024140
30    18987.382410
31    18601.397240
32    19232.175560
33    22739.426280
34    25719.147150
35    29198.055690
36    32738.262900
37    36144.481220
38    37446.486090
39    32755.176820
40    38420.522890
41    42334.711210
42    42665.255970
43    42676.468370
44    41039.893600
45    35175.188980
46    34229.193630
Name: per capita income (US$), dtype: float64

In [6]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,train_size=0.8,random_state=42)

In [9]:
pipeline = Pipeline(
     [
         ('polynomial',PolynomialFeatures(degree=4)),
         ('Scaler',StandardScaler()),
         ('model',LinearRegression())
     ]
)

In [10]:
X_train_list = [X_train]
pipeline.fit(X_train,Y_train)

Pipeline(steps=[('polynomial', PolynomialFeatures(degree=4)),
                ('Scaler', StandardScaler()), ('model', LinearRegression())])

In [61]:
pipeline.score(X_test,Y_test)

0.9602796918251266

In [62]:
pipeline.predict(X_test)

array([18349.66934274, 34816.70690059, 17240.50431751, 38531.36807178,
       15282.64975745, 30788.32356722, 10151.82010617, 11963.88801885,
        6648.5368766 , 16216.95527855])

In [65]:
joblib.dump(pipeline,'model.pkl')

['model.pkl']